CREATE VIEW v_Logs AS
     SELECT USUARIO.NOMBRE_USER, TIPO_PERFIL.NOMBRE_TIPO_PERFIL, ACCION_LOGS, DESCRIPCION_LOGS, FECHA_LOGS FROM LOGS
     INNER JOIN USUARIO ON LOGS.ID_USER_LOGS = USUARIO.DOC_USER
     INNER JOIN TIPO_PERFIL ON USUARIO.ID_PERFIL_USER = TIPO_PERFIL.ID_TIPO_PERFIL;
     
     